name: Trigger auto deployment for meeting-bot

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      - main
      - dev  # <-- Added dev branch so it triggers on your new branch!
    paths:
      - '**'
      - '.github/workflows/meeting-bot-AutoDeployTrigger-2fac314a-6f10-4da2-afcf-01aafd2c968d.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write # This is required for requesting the OIDC JWT Token
      contents: read  # Required when GH token is used to authenticate with private repo

    # Set the environment variables dynamically based on which branch triggered the workflow
    env:
      APP_NAME: ${{ github.ref == 'refs/heads/main' && 'meeting-bot' || 'meeting-bot-dev' }}
      RG_NAME: ${{ github.ref == 'refs/heads/main' && 'rg-container-prod' || 'rg-container-dev' }}

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.MEETINGBOT_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MEETINGBOT_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MEETINGBOT_AZURE_SUBSCRIPTION_ID }}

      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: Dockerfile
          registryUrl: ""
          registryUsername: ${{ secrets.MEETINGBOT_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MEETINGBOT_REGISTRY_PASSWORD }}
          
          # Pass the dynamic variables to the deployment step
          containerAppName: ${{ env.APP_NAME }}
          resourceGroup: ${{ env.RG_NAME }}
          imageToBuild: ${{ env.APP_NAME }}:${{ github.sha }}