name: Trigger auto deployment for meeting-bot-dev

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ dev ]
    paths:
    - '**'
    - '.github/workflows/meeting-bot-dev-AutoDeployTrigger-017c7cb6-625b-41df-8379-b8bf7dc0d124.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.MEETINGBOTDEV_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MEETINGBOTDEV_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MEETINGBOTDEV_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: 
          registryUsername: ${{ secrets.MEETINGBOTDEV_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MEETINGBOTDEV_REGISTRY_PASSWORD }}
          containerAppName: meeting-bot-dev
          resourceGroup: rg-container-dev
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


